[tool.poetry]
name = "uniflow"
version = "0.0.0"
description = "Unified flow interface for synthetic data generation and many more"
authors = ["CambioML <wanwanaiai45@gmail.com>"]
maintainers = ["Rachel Hu <goldpiggy@berkeley.edu>"]
license = "Apache License"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
spacy = "^3.7.0"
pandas = "2.0.3"
clean-text = "0.6.0"
python-dotenv = "^1.0.0"
lmqg = "0.1.1"
openai = "^0.28.1"
torch = "^1.12.1"
graphviz = "0.20.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
